### ISSUE TITLE
Failure/Error: raise BrowserNotFound, 'Failed to find Chrome binary.' を解決する

### ISSUE THREAD

**Issue by ryamakuchi** [ryamakuchi/my-encyclopaedia#7]
Capybara でのテスト実行時に以下のようなエラーが出てしまい、テストがこける。

```
Failure/Error: raise BrowserNotFound, 'Failed to find Chrome binary.'

          Webdrivers::BrowserNotFound:
            Failed to find Chrome binary.
```

## どういうエラー？

Chrome binary が見つからないよ、と言われているため、Chrome がないのが原因？？
そもそも Docker 環境内なので Chrome が入っていないと思われる。

**Comment by ryamakuchi** [comment]
とりあえず `brew cask install chromedriver` で ChromeDriver をインストールしてみた。

```
==> Installing Cask chromedriver
==> Linking Binary 'chromedriver' to '/usr/local/bin/chromedriver'.
🍺  chromedriver was successfully installed!
```

**Comment by ryamakuchi** [comment]
## 最終的な設定

```ruby
# spec/support/capybara.rb

RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :rack_test
  end

  config.before(:each, type: :system, js: true) do
    if ENV["SELENIUM_DRIVER_URL"].present?
      driven_by :selenium, using: :chrome, options: {
        browser: :remote,
        url: ENV.fetch("SELENIUM_DRIVER_URL"),
        desired_capabilities: :chrome
      }
    else
      driven_by :selenium_chrome_headless
    end
  end
end
```

```yml
# docker-compose.yml

version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ..
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - ..:/app
    ports:
    - "3000:3000"
    depends_on:
    - db
# selenium_chrome を使うために以下の行を追加
    environment:
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
```

```yml
# .circleci/config.yml

...

    - image: selenium/standalone-chrome-debug
      logging:
        driver: none

...
```

こちらを設定して開発環境でも CircleCI でもテストが通ることを確認。
よしゃ！ 💪
